const actions = {
  ADD_TO_CART: "ADD_TO_CART",
  SET_PRODUCTS: "SET_PRODUCTS",
  CHANGE_CART_ITEM_AMOUNT: "CHANGE_CART_ITEM_AMOUNT",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  CHANGE_CART_VISIBILITY: "CHANGE_CART_VISIBILITY",
  CHANGE_PROMO_PERCENT: "CHANGE_PROMO_PERCENT",
  CHANGE_PROMO_CODE_CORRECT: "CHANGE_PROMO_CODE_CORRECT",
}

export default actions;